In [2]:
import pandas as pd
import numpy as np

In [3]:
rev_ba = pd.read_csv('./data/BeerAdvocate/ratings-without-text.csv', nrows=8393032)

In [4]:
df_ba = pd.read_csv('./data/BA_groups.csv')

In [7]:
# Add year to reviews (corresponds to timestamp 'data')
rev_ba['year'] = pd.to_datetime(rev_ba['date'], unit='s').dt.year
rev_ba['year'] = rev_ba['year'].astype(np.int64)

big_ba = df_ba[["year","brewery_name", "main_group"]]
ba_big_ratings = rev_ba.merge(big_ba, how='left', on=["brewery_name", "year"])

Empty DataFrame
Columns: [beer_name, beer_id, brewery_name, brewery_id, style, abv, date, user_name, user_id, appearance, aroma, palate, taste, overall, rating, review, year, main_group]
Index: []

In [10]:
# Sanity check
ba_big_ratings[ba_big_ratings['brewery_name']=='Brauerei Diebels GmbH & Co KG'].head(3)

,beer_name,beer_id,brewery_name,brewery_id,style,abv,date,user_name,user_id,appearance,aroma,palate,taste,overall,rating,review,year,main_group
700276,Diebels Alt,6061,Brauerei Diebels GmbH & Co KG,2418,Altbier,4.8,1474106400,JTuomi,jtuomi.772206,4.00,3.75,3.5,3.75,3.75,3.74,False,2016,InBev
700277,Diebels Alt,6061,Brauerei Diebels GmbH & Co KG,2418,Altbier,4.8,1463392800,BlackVeg,blackveg.1133276,4.50,3.50,1.5,1.50,1.75,2.21,False,2016,InBev
700278,Diebels Alt,6061,Brauerei Diebels GmbH & Co KG,2418,Altbier,4.8,1459418400,Ac-dx,ac-dx.1123807,3.75,3.50,3.5,3.50,3.50,3.52,False,2016,InBev

In [11]:
ba_big_ratings.to_csv('./data/BeerAdvocate/ratings_big.csv', index=False)

:

In [2]:
df_rb = pd.read_csv('./data/RB_groups.csv')
rev_rb = pd.read_csv('./data/RateBeer/ratings-without-text.csv', nrows=7122074)

In [3]:
# Add year to reviews (corresponds to timestamp 'data')
rev_rb['year'] = pd.to_datetime(rev_rb['date'], unit='s').dt.year
rev_rb['year'] = rev_rb['year'].astype(np.int64)

big_rb = df_rb[["year","brewery_name", "main_group"]]
rb_big_ratings = rev_rb.merge(big_rb, how='left', on=["brewery_name", "year"]) 

# Sanity check
rb_big_ratings[rb_big_ratings['brewery_name']=='Falcon Bryggerier (Carlsberg)'].head(3)

,beer_name,beer_id,brewery_name,brewery_id,style,abv,date,user_name,user_id,appearance,aroma,palate,taste,overall,rating,year,main_group
2254596,Falcon Gammelbrygd (-1996),11607,Falcon Bryggerier (Carlsberg),2064,Dunkel/Tmavý,5.5,1420974000,Leini,242267,3,7,3,7,13,3.3,2015,Carslberg
2254597,Falcon Gammelbrygd (-1996),11607,Falcon Bryggerier (Carlsberg),2064,Dunkel/Tmavý,5.5,1401789600,AndySnow,123903,4,8,3,7,13,3.5,2014,Carslberg
2254598,Falcon Gammelbrygd (-1996),11607,Falcon Bryggerier (Carlsberg),2064,Dunkel/Tmavý,5.5,1284199200,oh6gdx,19328,4,8,4,8,16,4.0,2010,Carslberg

In [5]:
rb_big_ratings.to_csv('./data/RateBeer/ratings_big.csv', index=False)

In [ ]:
# Add year to reviews (corresponds to timestamp 'data')
rev_ba['year'] = pd.to_datetime(rev_ba['date'], unit='s').dt.year
rev_ba['year'] = rev_ba['year'].astype(np.int64)

big_ba = df_ba[["year","brewery_name", "main_group"]]
ba_big_ratings = rev_ba.merge(big_ba, how='left', on=["brewery_name", "year"]) 

# Sanity check
ba_big_ratings[ba_big_ratings['brewery_name']=='Falcon Bryggerier (Carlsberg)'].head(3)

In [21]:
rev_rb.to_csv('./data/RateBeer/ratings_big.csv', index=False)